fogbender/b2b-saaskit

src/pages/b2b-saaskit/01_doppler.md
Let's see if `gh pr create -a jlarky` works
=> Copy for step 1 (Doppler)

package.json, src/components/head/Posthog.astro, src/components/head/posthog.ts, src/layouts/Layout.astro, src/lib/posthog.ts, src/lib/trpc/routers/prompts.ts, src/pages/setup/b2b-saaskit/06_posthog.md, src/pages/setup/index.astro, src/t3-env.ts
added posthog event tracking and postghog section in the tutorial
=> service: posthog

src/components/app/Nav.tsx
=> show support link in the navbar on support page

src/components/fogbender/Support.tsx, src/pages/app/_envCheck.ts, src/pages/app/index.astro, src/pages/app/prompts.astro, src/pages/app/settings.astro, src/pages/app/support.astro
=> improve env check error message

src/pages/eject/index.astro
- add a bit of explanation
- save last open section in localstorage for /eject
=> improve /eject

src/components/app/Nav.tsx, src/components/propelauth.tsx
- make it more accessible
- add keyboard navigation
- Escape key to close menu
- add Organization link
- improve redirect to /app to fix infinite loop
=> improve nav menu in app

src/content/setup/posthog.md, src/content/setup/production.md
=> improve posthog production instructions

src/components/app/Prompts.tsx, src/content/setup/openai.md, src/content/setup/production.md, src/db/migrations/0006_good_george_stacy.sql, src/db/migrations/meta/0006_snapshot.json, src/db/migrations/meta/_journal.json, src/db/schema.ts, src/lib/trpc/routers/prompts.ts, src/pages/setup/index.astro, src/t3-env.ts
- open ai instructions
- add shared_key_ratelimit table
- allow 3 free prompts per day using a default key
=> set default openai key if users don't have their own

.github/actions/prepare/action.yml, .github/workflows/lint.yml, .github/workflows/prettier.yml
=> feat: Add lint CI job

src/components/app/BrowserRouter.tsx, src/components/app/CreatePrompt.tsx, src/components/app/EditPrompt.tsx, src/components/app/Layout.tsx, src/components/app/Prompt.tsx, src/components/app/Prompts.tsx, src/components/app/Settings.tsx, src/components/app/routes.tsx, src/components/app/utils.ts, src/components/trpc.tsx, src/content/eject/b2bsaaskit.md, src/db/migrations/0007_giant_greymalkin.sql, src/db/migrations/meta/0007_snapshot.json, src/db/migrations/meta/_journal.json, src/db/schema.ts, src/lib/router.tsx, src/lib/trpc/root.ts, src/lib/trpc/routers/prompts.ts, src/pages/api/orgs/[orgId].ts, src/pages/app/index.astro, src/pages/app/prompts.astro, src/pages/app/prompts/[id].astro, src/pages/app/prompts/[id]/edit.astro, src/pages/app/prompts/create.astro, src/pages/app/settings.astro, src/pages/app/support.astro, src/pages/demo/trpc/create_caller.astro, src/pages/demo/trpc/create_caller.json.ts, src/pages/demo/trpc/create_helpers.astro, src/pages/demo/trpc/custom_errors.astro
=> new UI for prompts

src/components/app/Prompts.tsx, src/components/app/routes.tsx, src/lib/trpc/routers/prompts.ts
- do not crash on errors in /app/prompts
- update optimistic update example using example from docs
- update updatedAt
=> some improvements :)

src/components/landing/B2B.astro
> Add a GitHub corner ribbon around the landing page
=> feat: Add github corner ribbon

src/components/Login.tsx, src/components/Signup.tsx, src/components/app/App.tsx, src/components/app/Prompt.tsx, src/components/app/utils.ts
if you open public prompt page and try to like it you will be sent to login page, once you login you will be redirected back to original public page (it won't try to like the page again automatically like reddir or stackoverflow usually do though)
=> implment returnUrl to get back to the page we were on before

.eslintrc.cjs, src/components/app/AppLayout.astro, src/components/head/SEO.astro, src/pages/api/orgs/[orgId].ts, src/pages/og/_openGraphPrompt.tsx, src/pages/og/index.ts, src/pages/prompts/[promptId].astro
include prompt data in the og:image
=> og images for public prompts

src/components/app/Settings.tsx, src/components/survey/Survey.tsx, src/components/trpc.tsx, src/lib/trpc/routers/hello.ts, src/lib/trpc/routers/prompts.ts, src/lib/trpc/routers/settings.ts, src/pages/og/_openGraph.tsx, src/pages/setup/index.astro
=> feat: Code cleanup

src/content/setup/production.md, src/content/setup/propelauth.md
So that we can show names instead of ids for users :)
=> ask for name and profile url in propel

src/components/app/CreatePrompt.tsx, src/components/app/EditPrompt.tsx, src/components/app/Prompt.tsx, src/components/app/Prompts.tsx, src/components/app/Settings.tsx, src/components/fogbender/Support.tsx, src/lib/trpc/routers/prompts.ts
- [remove comments, restyle description and author](https://github.com/fogbender/b2b-saaskit/commit/fe8beab8f09387bfd6366b79d076ea590c20de9c)
- [make likes nicer](https://github.com/fogbender/b2b-saaskit/commit/8105919ad5e238d62836c7bc6cbff2a7243d91f9)
- [update titles to be in a format "prompts with friends / stuff"](https://github.com/fogbender/b2b-saaskit/commit/dd001ffeae5b975be2b3c19ac36a57e8c9124482)
- [add regenerate button, add global progress indicator](https://github.com/fogbender/b2b-saaskit/commit/14edf3bfa37267e54d0970d55112ed0755ba4998)
=> remove comments, like button, regenerate button

src/components/app/CreatePrompt.tsx, src/components/app/Prompt.tsx
=> Fix Saveing; show JSON to make it clearer what 'copy' means

src/components/app/Prompts.tsx, src/lib/trpc/routers/prompts.ts, src/pages/prompts/[promptId].astro, src/pages/prompts/index.astro
Show 100 prompts that were last created
=> public prompts

src/components/landing/B2B.astro, src/layouts/Layout.astro
> This Pull request will fix some CSS style gaps and will clean up CSS classes
> Prevent the over-scrolling for screens larger than `768px`.
> Show scrollbar if the content is larger than the available space in `pre` element
> Remove duplicate CSS class getting applied for same screen size
https://github.com/fogbender/b2b-saaskit/assets/47587853/16e9d44a-3018-4d33-8044-6ebcb6a64379
=> fix: Fixed styling gaps and bugs

src/components/app/Prompts.tsx, src/components/app/Settings.tsx
=> feat: Code fixes

src/content/setup/doppler.md, src/content/setup/github_oauth.md, src/content/setup/production.md
Also not sure why all the steps aren't numbered in the doppler md file, but renders out fine in the app
=> docs fixes

src/components/setup/SetupStep.astro, src/content/eject/astro.md, src/content/eject/b2bsaaskit.md, src/content/eject/doppler.md, src/content/eject/drizzle.md, src/content/eject/eslint.md, src/content/eject/fogbender.md, src/content/eject/github.md, src/content/eject/posthog.md, src/content/eject/prettier.md, src/content/eject/propel.md, src/content/eject/react.md, src/content/eject/stripe.md, src/content/eject/supabase.md, src/content/eject/tailwind.md, src/content/eject/trpc.md, src/content/eject/vercel.md, src/pages/eject/index.astro, src/pages/setup/index.astro
- make setup/eject sections linkable
- add docs for a lot of sections
- leave TODO in the rest of the sections
=> eject docs

src/lib/trpc/routers/prompts.ts
do not show private prompts in the list if you don't have access to them
=> Bug  privacy level in prompts

src/components/app/EditPrompt.tsx, src/components/app/Prompt.tsx, src/components/app/Prompts.tsx, src/components/app/usePromptErrorPage.tsx, src/lib/trpc/routers/prompts.ts
- add error page to edit prompt page
- add "(You)" to own prompts
- improve error message when trying to edit prompts you don't own
=> improve error messages

src/components/app/CreatePrompt.tsx
=> return limit couter

src/components/PropelAuthCSS.tsx, src/components/app/App.tsx, src/pages/login-passwordless.astro, src/pages/login.astro
=> improve app landing page

package.json, src/components/app/App.tsx, src/components/app/routes.tsx, src/components/app/store.ts, yarn.lock
Show this error message if we didn't hear anything from Propel for more than 3 seconds
please merge #138 first
=> handle stuck PropelAuth
